USE SCHEMA SRC_FOX;

CREATE OR REPLACE PROCEDURE "SP_FOXIMPORT"("PIPELINE_ID" VARCHAR(16777216), "PIPELINE_NAME" VARCHAR(16777216), "DB_NAME" VARCHAR(16777216), "UTIL_SC" VARCHAR(16777216), "TGT_SC" VARCHAR(16777216), "LZ_FOX_SC" VARCHAR(16777216), "WH" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE


V_SP_PROCESS_RUN_LOGS_DTL  VARCHAR := :DB_NAME||''.''||COALESCE(:UTIL_SC, ''UTIL'')||''.SP_PROCESS_RUN_LOGS_DTL'';

V_PROGRAM_LIST  VARCHAR := :DB_NAME||''.''||COALESCE(:UTIL_SC, ''UTIL'')||''.PROGRAM_LIST'';

V_PROCESS_NAME     VARCHAR := ''FOXIMPORT''; 

V_SUB_PROCESS_NAME VARCHAR DEFAULT ''FOXIMPORT'';

V_STEP             VARCHAR;

V_STEP_NAME        VARCHAR;

V_START_TIME       VARCHAR;

V_END_TIME         VARCHAR;

V_ROWS_PARSED       INTEGER;

V_ROWS_LOADED       INTEGER;

V_MESSAGE          VARCHAR;

V_LAST_QUERY_ID    VARCHAR;

V_FOXIMPORT_STG   VARCHAR := :DB_NAME||''.''||COALESCE(:LZ_FOX_SC, ''LZ_FOX'')||''.FOXIMPORT_STG'';

V_FOXIMPORT VARCHAR := :DB_NAME||''.''||COALESCE(:TGT_SC, ''SRC_FOX'')||''.FOXIMPORT'';



BEGIN

ALTER SESSION SET TIMEZONE = ''America/Chicago'';

   V_STEP := ''STEP1'';
   
   V_STEP_NAME := ''LOAD FOXIMPORT'';
   
   V_START_TIME := CONVERT_TIMEZONE(''America/Chicago'', CURRENT_TIMESTAMP());

EXECUTE IMMEDIATE ''USE WAREHOUSE ''||:WH;
   
   V_ROWS_PARSED  := (SELECT COUNT(1) FROM IDENTIFIER(:V_FOXIMPORT_STG) );

INSERT INTO IDENTIFIER(:V_FOXIMPORT)
(
CLM_NUM,
CLH_TRK_ID,
MEDCR_CLM_CTL_NBR,
INST_PROF_IND,
ORIG_MBR_NBR,
DOC_CTL_NBR,
CLM_STAT,
DT_CMPLTD,
SRV_FROM_DT,
SRV_TO_DT,
FCLTY_CD,
CREATE_DT,
ACCT_NBR,
CLM_RECPT_DT
)   
     
SELECT 
clm_num,
clh_trk_id,
medcr_clm_ctl_nbr,
inst_prof_ind,
orig_mbr_nbr,
doc_ctl_nbr,
clm_stat,
trim(substr(dt_cmpltd,1,19)) as dt_cmpltd,
trim(substr(srv_from_dt,1,19)) as srv_from_dt,
trim(substr(srv_to_dt,1,19)) as srv_to_dt,
fclty_cd,
trim(substr(creat_dt,1,19)) as create_dt,
acct_nbr as acct_nbr,
trim(substr(clm_recpt_dt,1,10)) as clm_recpt_dt from IDENTIFIER(:V_FOXIMPORT_STG)
;



V_ROWS_LOADED := SQLROWCOUNT ;

V_LAST_QUERY_ID := (SELECT LAST_QUERY_ID(-1)) ;
   

   
CALL IDENTIFIER(:V_SP_PROCESS_RUN_LOGS_DTL) (:DB_NAME, :UTIL_SC, ''PRE_CLM'' , :PIPELINE_ID, :PIPELINE_NAME, :V_PROCESS_NAME, :V_SUB_PROCESS_NAME, 
                                 :V_STEP, :V_STEP_NAME, :V_START_TIME, CURRENT_TIMESTAMP(), ''SUCCESS'', :V_LAST_QUERY_ID, :V_ROWS_PARSED, :V_ROWS_LOADED, NULL, NULL, NULL);




EXCEPTION

WHEN OTHER THEN

CALL IDENTIFIER(:V_SP_PROCESS_RUN_LOGS_DTL) (:DB_NAME, :UTIL_SC, ''PRE_CLM'' , :PIPELINE_ID, :PIPELINE_NAME,  :V_PROCESS_NAME, :V_SUB_PROCESS_NAME,
                                 :V_STEP, :V_STEP_NAME, :V_START_TIME, CURRENT_TIMESTAMP(), ''FAILED'', :V_LAST_QUERY_ID, NULL, NULL, :SQLERRM, :SQLCODE, :SQLSTATE);


RAISE;

END;

';