config-version: 1

# The modules folder for jinja macros and templates to be used across multiple scripts.
modules-folder: null

# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
snowflake-account: {{ env_var('SNOWFLAKE_ACCOUNT') }}

# The name of the snowflake user
snowflake-user: {{ env_var('SNOWFLAKE_USER') }}

# The name of the default role to use. Can be overrideen in the change scripts.
snowflake-role: {{ env_var('SNOWFLAKE_ROLE') }}

# The name of the default warehouse to use. Can be overridden in the change scripts.
snowflake-warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}

# The name of the default database to use. Can be overridden in the change scripts.
snowflake-database: {{ env_var('SNOWFLAKE_DATABASE') }}

# Create the change history schema and table, if they do not exist (the default is False)
create-change-history-table: true

# Display verbose debugging details during execution (the default is False)
verbose: false

# Run schemachange in dry run mode (the default is False)
dry-run: false

vars:
  env: {{ env_var('DEPLOYMENT_ENV_PREFIX') }}