USE SCHEMA UTIL;

CREATE or REPLACE FILE FORMAT FF_DATA_EXTRACT_PIPE_CSV_NO_HEADER 
    TYPE = 'CSV' 
    COMPRESSION = 'AUTO' 
    FIELD_DELIMITER = '|' 
    RECORD_DELIMITER = '\n' 
    SKIP_HEADER = 0