USE SCHEMA UTIL;
CREATE OR REPLACE FILE FORMAT FF_COMMA_CSV
	ESCAPE_UNENCLOSED_FIELD = 'NONE'
	TRIM_SPACE = TRUE
	NULL_IF = ('null', 'NULL', '\\N')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ENCODING = 'WINDOWS1252'
;

CREATE OR REPLACE FILE FORMAT FF_DATA_EXTRACT_PIPE_CSV
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	ESCAPE_UNENCLOSED_FIELD = 'NONE'
	TRIM_SPACE = TRUE
	NULL_IF = ('null', 'NULL', '\\N')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ENCODING = 'WINDOWS1252'
COMMENT='Usage: Load on prem data to snowflake'
;


CREATE OR REPLACE FILE FORMAT FF_PIPE_CSV
	FIELD_DELIMITER = '|'
	ESCAPE_UNENCLOSED_FIELD = 'NONE'
	TRIM_SPACE = TRUE
	NULL_IF = ('null', 'NULL', '\\N')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ENCODING = 'WINDOWS1252'
COMMENT='Usage: Load mspdp files to snowflake'
;


CREATE OR REPLACE FILE FORMAT FF_SOH_CSV
	TYPE = csv
	FIELD_DELIMITER = '\u0001'
	NULL_IF = ('NULL', 'null', '\\N')
COMMENT='Usage: EDI Legacy Data Load'
;


CREATE OR REPLACE FILE FORMAT FF_TILDA_CSV
	FIELD_DELIMITER = '~'
	ESCAPE_UNENCLOSED_FIELD = 'NONE'
	TRIM_SPACE = TRUE
	NULL_IF = ('null', 'NULL', '\\N')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ENCODING = 'WINDOWS1252'
;
