USE SCHEMA UTIL;
CREATE OR REPLACE FILE FORMAT FF_DATA_EXTRACT_PIPE_CSV
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	ESCAPE_UNENCLOSED_FIELD = 'NONE'
	TRIM_SPACE = TRUE
	NULL_IF = ()
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ENCODING = 'WINDOWS1252'
    COMMENT = 'Usage: Load on prem data to snowflake'
;
