USE SCHEMA UTIL;

CREATE OR REPLACE FILE FORMAT FF_SOH_CSV TYPE = 'csv' FIELD_DELIMITER = '' NULL_IF = ('NULL','null', '\N', '\\N')
	    COMMENT = 'Usage: EDI Legacy Data Load'
;

create table if not exists LEGACY_LOAD (
	TABLE_NAME VARCHAR(16777216),
	TRAN_MTH VARCHAR(16777216),
	LOAD_INDC VARCHAR(16777216)
);
