use schema SRC_FOX;


create TABLE IF NOT EXISTS DB2IMPORT (
	CLM_PART_DT VARCHAR(16777216),
	CLM_INFO_KEY VARCHAR(16777216),
	UCPS_CLM_NUM VARCHAR(16777216),
	CLM_TYPE VARCHAR(16777216),
	REF_ID_QLFR VARCHAR(16777216),
	REF_ID_VALUE VARCHAR(16777216),
	MEMBER_ID VARCHAR(16777216),
	CREAT_DT VARCHAR(16777216),
	UCPS_CLM_DT VARCHAR(16777216),
	ISDC_CREATED_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	ISDC_UPDATED_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace view CH_VIEW(
	CLM_NUM,
	CLH_TRK_ID,
	MEDICARE_CLM_CNTRL_NUM,
	CLM_TYPE,
	MEMBER_ID,
	CLM_RECEPT_DT,
	DOC_CTL_NBR
) as
SELECT
     A.UCPS_CLM_NUM  AS  CLM_NUM ,
     A.NETWORK_TRACE_NUMBER  AS  CLH_TRK_ID ,
     A.MEDCR_CLM_CTL_NBR  AS  MEDICARE_CLM_CNTRL_NUM ,
     A.CLM_TYPE  AS  CLM_TYPE ,
     A.MEMBER_ID  AS  MEMBER_ID ,
     A.CLM_RECEPT_DT ,
    NULL AS  DOC_CTL_NBR FROM (
      
      
    SELECT
        DISTINCT  DB2IMPORT . UCPS_CLM_NUM ,
         DB2IMPORT . REF_ID_VALUE  AS  NETWORK_TRACE_NUMBER ,
         NULL AS  MEDCR_CLM_CTL_NBR ,
         DB2IMPORT.CLM_TYPE ,
         DB2IMPORT.MEMBER_ID  AS  MEMBER_ID ,
         DB2IMPORT.UCPS_CLM_DT  AS  CLM_RECEPT_DT 
    FROM
         SRC_FOX.DB2IMPORT DB2IMPORT
    WHERE
         DB2IMPORT.REF_ID_QLFR  = 'D9'
         
         UNION


    SELECT
        DISTINCT  DB2IMPORT.UCPS_CLM_NUM ,
         NULL AS  NETWORK_TRACE_NUMBER ,
         DB2IMPORT.REF_ID_VALUE  AS  MEDCR_CLM_CTL_NBR ,
         DB2IMPORT.CLM_TYPE ,
         DB2IMPORT.MEMBER_ID  AS  MEMBER_ID ,
         DB2IMPORT.UCPS_CLM_DT  AS  CLM_RECEPT_DT 
    FROM
         SRC_FOX.DB2IMPORT DB2IMPORT
    WHERE
         DB2IMPORT.REF_ID_QLFR  = 'F8'
      ) A
GROUP BY
     A.UCPS_CLM_NUM ,
     A.NETWORK_TRACE_NUMBER ,
     A.MEDCR_CLM_CTL_NBR ,
     A.CLM_TYPE ,
     A.MEMBER_ID ,
     A.CLM_RECEPT_DT 
  
UNION
SELECT
     FOXIMPORT . CLM_NUM ,
    TRIM( FOXIMPORT . CLH_TRK_ID ) AS  CLH_TRK_ID ,
    TRIM( FOXIMPORT . MEDCR_CLM_CTL_NBR ) AS  MEDICARE_CLM_CNTRL_NUM ,
     FOXIMPORT . INST_PROF_IND ,
    TRIM( FOXIMPORT . ORIG_MBR_NBR ) AS  MEMBER_ID ,
     FOXIMPORT . CLM_RECPT_DT ,
     FOXIMPORT . DOC_CTL_NBR 
FROM
     SRC_FOX.FOXIMPORT FOXIMPORT;
